apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hello-node-deployment
  namespace: myapp
  labels:
    app:  hello-node
spec:
  selector:
    matchLabels:
      app: hello-node
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  hello-node
    spec:
      containers:
      - name:  hello-node
        image:  soloetzgh/agronode:17
        imagePullPolicy: Always
        ports:
        - containerPort:  8080
          name: hello-node